# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design/adminEntry.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(721, 910)
        Form.setStyleSheet("background-color: rgb(255,255,255)")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(5, 0, 5, 9)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 709, 899))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../image/enavi_header.png"))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.qaBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.qaBtn.setStyleSheet("background-color: rgb(0,255,255)")
        self.qaBtn.setObjectName("qaBtn")
        self.verticalLayout.addWidget(self.qaBtn)
        self.dbBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.dbBtn.setStyleSheet("background-color: rgb(0,255,255)")
        self.dbBtn.setObjectName("dbBtn")
        self.verticalLayout.addWidget(self.dbBtn)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.fieldList = QtWidgets.QListWidget(self.scrollAreaWidgetContents_2)
        self.fieldList.setObjectName("fieldList")
        item = QtWidgets.QListWidgetItem()
        self.fieldList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.fieldList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.fieldList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.fieldList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.fieldList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.fieldList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.fieldList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.fieldList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.fieldList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.fieldList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.fieldList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.fieldList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.fieldList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.fieldList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.fieldList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.fieldList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.fieldList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.fieldList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.fieldList.addItem(item)
        self.verticalLayout_6.addWidget(self.fieldList)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.fieldAddBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.fieldAddBtn.setObjectName("fieldAddBtn")
        self.horizontalLayout_6.addWidget(self.fieldAddBtn)
        self.fieldDelBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.fieldDelBtn.setObjectName("fieldDelBtn")
        self.horizontalLayout_6.addWidget(self.fieldDelBtn)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.gridLayout_2.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6)
        self.jobList = QtWidgets.QListWidget(self.scrollAreaWidgetContents_2)
        self.jobList.setObjectName("jobList")
        item = QtWidgets.QListWidgetItem()
        self.jobList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.jobList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.jobList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.jobList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.jobList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.jobList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.jobList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.jobList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.jobList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.jobList.addItem(item)
        self.verticalLayout_7.addWidget(self.jobList)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.jobAddBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.jobAddBtn.setObjectName("jobAddBtn")
        self.horizontalLayout_7.addWidget(self.jobAddBtn)
        self.jobDelBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.jobDelBtn.setObjectName("jobDelBtn")
        self.horizontalLayout_7.addWidget(self.jobDelBtn)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.gridLayout_2.addLayout(self.verticalLayout_7, 0, 1, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_8.addWidget(self.label_7)
        self.teachList = QtWidgets.QListWidget(self.scrollAreaWidgetContents_2)
        self.teachList.setObjectName("teachList")
        item = QtWidgets.QListWidgetItem()
        self.teachList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.teachList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.teachList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.teachList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.teachList.addItem(item)
        self.verticalLayout_8.addWidget(self.teachList)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.teachAddBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.teachAddBtn.setObjectName("teachAddBtn")
        self.horizontalLayout_8.addWidget(self.teachAddBtn)
        self.teachDelBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.teachDelBtn.setObjectName("teachDelBtn")
        self.horizontalLayout_8.addWidget(self.teachDelBtn)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.gridLayout_2.addLayout(self.verticalLayout_8, 1, 1, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_9.addWidget(self.label_8)
        self.generalList = QtWidgets.QListWidget(self.scrollAreaWidgetContents_2)
        self.generalList.setObjectName("generalList")
        item = QtWidgets.QListWidgetItem()
        self.generalList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.generalList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.generalList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.generalList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.generalList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.generalList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.generalList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.generalList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.generalList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.generalList.addItem(item)
        self.verticalLayout_9.addWidget(self.generalList)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.genAddBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.genAddBtn.setObjectName("genAddBtn")
        self.horizontalLayout_9.addWidget(self.genAddBtn)
        self.genDelBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.genDelBtn.setObjectName("genDelBtn")
        self.horizontalLayout_9.addWidget(self.genDelBtn)
        self.verticalLayout_9.addLayout(self.horizontalLayout_9)
        self.gridLayout_2.addLayout(self.verticalLayout_9, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.endBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.endBtn.setObjectName("endBtn")
        self.horizontalLayout_4.addWidget(self.endBtn)
        self.applyBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.applyBtn.setObjectName("applyBtn")
        self.horizontalLayout_4.addWidget(self.applyBtn)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "管理者画面（エントリー編集）"))
        self.qaBtn.setText(_translate("Form", "質問"))
        self.dbBtn.setText(_translate("Form", "企業DB"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">業種コンボボックス</span></p></body></html>"))
        __sortingEnabled = self.fieldList.isSortingEnabled()
        self.fieldList.setSortingEnabled(False)
        item = self.fieldList.item(0)
        item.setText(_translate("Form", "農業，林業"))
        item = self.fieldList.item(1)
        item.setText(_translate("Form", "漁業"))
        item = self.fieldList.item(2)
        item.setText(_translate("Form", "鉱業，採石業，砂利採取業"))
        item = self.fieldList.item(3)
        item.setText(_translate("Form", "建設業"))
        item = self.fieldList.item(4)
        item.setText(_translate("Form", "製造業"))
        item = self.fieldList.item(5)
        item.setText(_translate("Form", "電気・ガス・熱供給・水道業"))
        item = self.fieldList.item(6)
        item.setText(_translate("Form", "情報通信業"))
        item = self.fieldList.item(7)
        item.setText(_translate("Form", "運輸業・郵便業"))
        item = self.fieldList.item(8)
        item.setText(_translate("Form", "卸売業，小売業"))
        item = self.fieldList.item(9)
        item.setText(_translate("Form", "金融業，保険業"))
        item = self.fieldList.item(10)
        item.setText(_translate("Form", "不動産業，物品賃貸業"))
        item = self.fieldList.item(11)
        item.setText(_translate("Form", "学術研究，専門・技術サービス業"))
        item = self.fieldList.item(12)
        item.setText(_translate("Form", "宿泊業，飲食サービス業"))
        item = self.fieldList.item(13)
        item.setText(_translate("Form", "生活関連サービス業，娯楽業"))
        item = self.fieldList.item(14)
        item.setText(_translate("Form", "教育，学習支援業"))
        item = self.fieldList.item(15)
        item.setText(_translate("Form", "医療，福祉"))
        item = self.fieldList.item(16)
        item.setText(_translate("Form", "複合サービス事業"))
        item = self.fieldList.item(17)
        item.setText(_translate("Form", "サービス業"))
        item = self.fieldList.item(18)
        item.setText(_translate("Form", "公務"))
        self.fieldList.setSortingEnabled(__sortingEnabled)
        self.fieldAddBtn.setText(_translate("Form", "追加"))
        self.fieldDelBtn.setText(_translate("Form", "削除"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">職種コンボボックス</span></p></body></html>"))
        __sortingEnabled = self.jobList.isSortingEnabled()
        self.jobList.setSortingEnabled(False)
        item = self.jobList.item(0)
        item.setText(_translate("Form", "営業職"))
        item = self.jobList.item(1)
        item.setText(_translate("Form", "企画管理"))
        item = self.jobList.item(2)
        item.setText(_translate("Form", "事務・アシスタント"))
        item = self.jobList.item(3)
        item.setText(_translate("Form", "販売・サービス職"))
        item = self.jobList.item(4)
        item.setText(_translate("Form", "専門職（コンサルティングファーム，専門事務所）"))
        item = self.jobList.item(5)
        item.setText(_translate("Form", "金融系専門職"))
        item = self.jobList.item(6)
        item.setText(_translate("Form", "公務員・教員・農林水産関連職"))
        item = self.jobList.item(7)
        item.setText(_translate("Form", "技術職"))
        item = self.jobList.item(8)
        item.setText(_translate("Form", "医療系専門職"))
        item = self.jobList.item(9)
        item.setText(_translate("Form", "クリエイター・クリエイティブ職"))
        self.jobList.setSortingEnabled(__sortingEnabled)
        self.jobAddBtn.setText(_translate("Form", "追加"))
        self.jobDelBtn.setText(_translate("Form", "削除"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">資格（教職）コンボボックス</span></p></body></html>"))
        __sortingEnabled = self.teachList.isSortingEnabled()
        self.teachList.setSortingEnabled(False)
        item = self.teachList.item(0)
        item.setText(_translate("Form", "教員免許高一種"))
        item = self.teachList.item(1)
        item.setText(_translate("Form", "教員免許中一種"))
        item = self.teachList.item(2)
        item.setText(_translate("Form", "教員免許小一種"))
        item = self.teachList.item(3)
        item.setText(_translate("Form", "教員免許幼一種"))
        item = self.teachList.item(4)
        item.setText(_translate("Form", "養護教諭一種"))
        self.teachList.setSortingEnabled(__sortingEnabled)
        self.teachAddBtn.setText(_translate("Form", "追加"))
        self.teachDelBtn.setText(_translate("Form", "削除"))
        self.label_8.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">資格（一般）コンボボックス</span></p></body></html>"))
        __sortingEnabled = self.generalList.isSortingEnabled()
        self.generalList.setSortingEnabled(False)
        item = self.generalList.item(0)
        item.setText(_translate("Form", "基本情報処理技術者"))
        item = self.generalList.item(1)
        item.setText(_translate("Form", "応用情報処理技術者"))
        item = self.generalList.item(2)
        item.setText(_translate("Form", "行政書士"))
        item = self.generalList.item(3)
        item.setText(_translate("Form", "司法書士"))
        item = self.generalList.item(4)
        item.setText(_translate("Form", "社会保険労務士"))
        item = self.generalList.item(5)
        item.setText(_translate("Form", "宅件建物取引士"))
        item = self.generalList.item(6)
        item.setText(_translate("Form", "簿記3級"))
        item = self.generalList.item(7)
        item.setText(_translate("Form", "簿記2級"))
        item = self.generalList.item(8)
        item.setText(_translate("Form", "介護福祉士"))
        item = self.generalList.item(9)
        item.setText(_translate("Form", "気象予報士"))
        self.generalList.setSortingEnabled(__sortingEnabled)
        self.genAddBtn.setText(_translate("Form", "追加"))
        self.genDelBtn.setText(_translate("Form", "削除"))
        self.endBtn.setText(_translate("Form", "終了"))
        self.applyBtn.setText(_translate("Form", "確定"))

