# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design/eclassTop.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_topView(object):
    def setupUi(self, topView):
        topView.setObjectName("topView")
        topView.resize(721, 910)
        topView.setStyleSheet("background-color: rgb(255,255,255);")
        self.gridLayout = QtWidgets.QGridLayout(topView)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(topView)
        self.scrollArea.setStyleSheet("border: none;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 721, 910))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.upperLayout = QtWidgets.QHBoxLayout()
        self.upperLayout.setObjectName("upperLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.upperLayout.addItem(spacerItem)
        self.upperLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.upperLabel.setText("")
        self.upperLabel.setPixmap(QtGui.QPixmap("../image/eclass_upper.png"))
        self.upperLabel.setObjectName("upperLabel")
        self.upperLayout.addWidget(self.upperLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.upperLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.upperLayout)
        self.buttonsLayout = QtWidgets.QHBoxLayout()
        self.buttonsLayout.setObjectName("buttonsLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonsLayout.addItem(spacerItem2)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.webdiskBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.webdiskBtn.setStyleSheet("border: none;")
        self.webdiskBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../image/webdisk_pc_btn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.webdiskBtn.setIcon(icon)
        self.webdiskBtn.setIconSize(QtCore.QSize(170, 70))
        self.webdiskBtn.setObjectName("webdiskBtn")
        self.gridLayout_7.addWidget(self.webdiskBtn, 1, 0, 1, 1)
        self.webmailBtn_63 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.webmailBtn_63.setStyleSheet("border: none;")
        self.webmailBtn_63.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../image/webmail_sp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.webmailBtn_63.setIcon(icon1)
        self.webmailBtn_63.setIconSize(QtCore.QSize(170, 70))
        self.webmailBtn_63.setObjectName("webmailBtn_63")
        self.gridLayout_7.addWidget(self.webmailBtn_63, 0, 2, 1, 1)
        self.webmailBtn_60 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.webmailBtn_60.setStyleSheet("border: none;")
        self.webmailBtn_60.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../image/webdisk_sp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.webmailBtn_60.setIcon(icon2)
        self.webmailBtn_60.setIconSize(QtCore.QSize(170, 70))
        self.webmailBtn_60.setObjectName("webmailBtn_60")
        self.gridLayout_7.addWidget(self.webmailBtn_60, 1, 1, 1, 1)
        self.duetBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.duetBtn.setStyleSheet("border: none;")
        self.duetBtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../image/duet_btn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.duetBtn.setIcon(icon3)
        self.duetBtn.setIconSize(QtCore.QSize(170, 70))
        self.duetBtn.setObjectName("duetBtn")
        self.gridLayout_7.addWidget(self.duetBtn, 2, 0, 1, 1)
        self.webmailBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.webmailBtn.setStyleSheet("border: none;")
        self.webmailBtn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../image/webmail_pc.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.webmailBtn.setIcon(icon4)
        self.webmailBtn.setIconSize(QtCore.QSize(170, 70))
        self.webmailBtn.setObjectName("webmailBtn")
        self.gridLayout_7.addWidget(self.webmailBtn, 0, 0, 1, 1)
        self.webmailBtn_59 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.webmailBtn_59.setStyleSheet("border: none;")
        self.webmailBtn_59.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../image/eclass_pc.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.webmailBtn_59.setIcon(icon5)
        self.webmailBtn_59.setIconSize(QtCore.QSize(170, 70))
        self.webmailBtn_59.setObjectName("webmailBtn_59")
        self.gridLayout_7.addWidget(self.webmailBtn_59, 2, 1, 1, 1)
        self.goGlobalBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.goGlobalBtn.setStyleSheet("border: none;")
        self.goGlobalBtn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../image/goglobal_btn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.goGlobalBtn.setIcon(icon6)
        self.goGlobalBtn.setIconSize(QtCore.QSize(170, 70))
        self.goGlobalBtn.setObjectName("goGlobalBtn")
        self.gridLayout_7.addWidget(self.goGlobalBtn, 4, 0, 1, 1)
        self.webMail_56 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.webMail_56.setStyleSheet("border: none;")
        self.webMail_56.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../image/eclass_sp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.webMail_56.setIcon(icon7)
        self.webMail_56.setIconSize(QtCore.QSize(170, 70))
        self.webMail_56.setObjectName("webMail_56")
        self.gridLayout_7.addWidget(self.webMail_56, 2, 2, 1, 1)
        self.webmailBtn_58 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.webmailBtn_58.setStyleSheet("border: none;")
        self.webmailBtn_58.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../image/password.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.webmailBtn_58.setIcon(icon8)
        self.webmailBtn_58.setIconSize(QtCore.QSize(170, 70))
        self.webmailBtn_58.setObjectName("webmailBtn_58")
        self.gridLayout_7.addWidget(self.webmailBtn_58, 1, 2, 1, 1)
        self.webmailBtn_64 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.webmailBtn_64.setStyleSheet("border: none;")
        self.webmailBtn_64.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../image/webmail_mb.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.webmailBtn_64.setIcon(icon9)
        self.webmailBtn_64.setIconSize(QtCore.QSize(170, 70))
        self.webmailBtn_64.setObjectName("webmailBtn_64")
        self.gridLayout_7.addWidget(self.webmailBtn_64, 0, 1, 1, 1)
        self.enaviBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.enaviBtn.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../image/enavi_btn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.enaviBtn.setIcon(icon10)
        self.enaviBtn.setIconSize(QtCore.QSize(170, 70))
        self.enaviBtn.setObjectName("enaviBtn")
        self.gridLayout_7.addWidget(self.enaviBtn, 4, 2, 1, 1)
        self.elearningBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.elearningBtn.setStyleSheet("border: none;")
        self.elearningBtn.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("../image/elearning_btn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.elearningBtn.setIcon(icon11)
        self.elearningBtn.setIconSize(QtCore.QSize(170, 70))
        self.elearningBtn.setObjectName("elearningBtn")
        self.gridLayout_7.addWidget(self.elearningBtn, 5, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("../image/ecareer_btn2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon12)
        self.pushButton.setIconSize(QtCore.QSize(170, 70))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_7.addWidget(self.pushButton, 4, 1, 1, 1)
        self.webmailBtn_61 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.webmailBtn_61.setStyleSheet("border: none;")
        self.webmailBtn_61.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("../image/fund_btn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.webmailBtn_61.setIcon(icon13)
        self.webmailBtn_61.setIconSize(QtCore.QSize(170, 70))
        self.webmailBtn_61.setObjectName("webmailBtn_61")
        self.gridLayout_7.addWidget(self.webmailBtn_61, 5, 1, 1, 1)
        self.buttonsLayout.addLayout(self.gridLayout_7)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonsLayout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.buttonsLayout)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../image/sso_footer.png"))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(topView)
        QtCore.QMetaObject.connectSlotsByName(topView)

    def retranslateUi(self, topView):
        _translate = QtCore.QCoreApplication.translate
        topView.setWindowTitle(_translate("topView", "同志社大学Webシングルサインオンシステム"))

