# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design/enaviEntry.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(724, 719)
        Form.setStyleSheet("background-color: rgb(255,255,255)")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(5, 0, 5, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 722, 701))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../image/enavi_header.png"))
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 3, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.fieldCombo1 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.fieldCombo1.setStyleSheet("QComboBox::item { background-color: rgb(200, 200, 200); }")
        self.fieldCombo1.setObjectName("fieldCombo1")
        self.horizontalLayout_4.addWidget(self.fieldCombo1)
        self.fieldCombo2 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.fieldCombo2.setStyleSheet("QComboBox::item { background-color: rgb(200, 200, 200); }")
        self.fieldCombo2.setObjectName("fieldCombo2")
        self.horizontalLayout_4.addWidget(self.fieldCombo2)
        self.fieldCombo3 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.fieldCombo3.setStyleSheet("QComboBox::item { background-color: rgb(200, 200, 200); }")
        self.fieldCombo3.setObjectName("fieldCombo3")
        self.horizontalLayout_4.addWidget(self.fieldCombo3)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 0, 2, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.genCombo1 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.genCombo1.setStyleSheet("QComboBox::item { background-color: rgb(200, 200, 200); }")
        self.genCombo1.setObjectName("genCombo1")
        self.horizontalLayout_11.addWidget(self.genCombo1)
        self.genCombo2 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.genCombo2.setStyleSheet("QComboBox::item { background-color: rgb(200, 200, 200); }")
        self.genCombo2.setObjectName("genCombo2")
        self.horizontalLayout_11.addWidget(self.genCombo2)
        self.genCombo3 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.genCombo3.setStyleSheet("QComboBox::item { background-color: rgb(200, 200, 200); }")
        self.genCombo3.setObjectName("genCombo3")
        self.horizontalLayout_11.addWidget(self.genCombo3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.teachCombo1 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.teachCombo1.setStyleSheet("QComboBox::item { background-color: rgb(200, 200, 200); }")
        self.teachCombo1.setObjectName("teachCombo1")
        self.horizontalLayout_12.addWidget(self.teachCombo1)
        self.teachCombo2 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.teachCombo2.setStyleSheet("QComboBox::item { background-color: rgb(200, 200, 200); }")
        self.teachCombo2.setObjectName("teachCombo2")
        self.horizontalLayout_12.addWidget(self.teachCombo2)
        self.teachCombo3 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.teachCombo3.setStyleSheet("QComboBox::item { background-color: rgb(200, 200, 200); }")
        self.teachCombo3.setObjectName("teachCombo3")
        self.horizontalLayout_12.addWidget(self.teachCombo3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_13.addWidget(self.label_12)
        self.toeicCombo = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.toeicCombo.setStyleSheet("QComboBox::item { background-color: rgb(200, 200, 200); }")
        self.toeicCombo.setObjectName("toeicCombo")
        self.horizontalLayout_13.addWidget(self.toeicCombo)
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_13.addWidget(self.label_13)
        self.toeflCombo = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.toeflCombo.setStyleSheet("QComboBox::item { background-color: rgb(200, 200, 200); }")
        self.toeflCombo.setObjectName("toeflCombo")
        self.horizontalLayout_13.addWidget(self.toeflCombo)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 3, 2, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.jobCombo1 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.jobCombo1.setStyleSheet("QComboBox::item { background-color: rgb(200, 200, 200); }")
        self.jobCombo1.setObjectName("jobCombo1")
        self.horizontalLayout.addWidget(self.jobCombo1)
        self.jobCombo2 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.jobCombo2.setStyleSheet("QComboBox::item { background-color: rgb(200, 200, 200); }")
        self.jobCombo2.setObjectName("jobCombo2")
        self.horizontalLayout.addWidget(self.jobCombo2)
        self.jobCombo3 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.jobCombo3.setStyleSheet("QComboBox::item { background-color: rgb(200, 200, 200); }")
        self.jobCombo3.setObjectName("jobCombo3")
        self.horizontalLayout.addWidget(self.jobCombo3)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 2, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.radioButton_95 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_95.setChecked(False)
        self.radioButton_95.setAutoExclusive(False)
        self.radioButton_95.setObjectName("radioButton_95")
        self.horizontalLayout_23.addWidget(self.radioButton_95)
        self.radioButton_96 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_96.setAutoExclusive(False)
        self.radioButton_96.setObjectName("radioButton_96")
        self.horizontalLayout_23.addWidget(self.radioButton_96)
        self.radioButton_97 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_97.setAutoExclusive(False)
        self.radioButton_97.setObjectName("radioButton_97")
        self.horizontalLayout_23.addWidget(self.radioButton_97)
        self.radioButton_98 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_98.setAutoExclusive(False)
        self.radioButton_98.setObjectName("radioButton_98")
        self.horizontalLayout_23.addWidget(self.radioButton_98)
        self.radioButton_99 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_99.setAutoExclusive(False)
        self.radioButton_99.setObjectName("radioButton_99")
        self.horizontalLayout_23.addWidget(self.radioButton_99)
        self.radioButton_100 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_100.setAutoExclusive(False)
        self.radioButton_100.setObjectName("radioButton_100")
        self.horizontalLayout_23.addWidget(self.radioButton_100)
        self.radioButton_101 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_101.setAutoExclusive(False)
        self.radioButton_101.setObjectName("radioButton_101")
        self.horizontalLayout_23.addWidget(self.radioButton_101)
        self.radioButton_102 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_102.setAutoExclusive(False)
        self.radioButton_102.setObjectName("radioButton_102")
        self.horizontalLayout_23.addWidget(self.radioButton_102)
        self.verticalLayout_5.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.radioButton_118 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_118.setAutoExclusive(False)
        self.radioButton_118.setObjectName("radioButton_118")
        self.horizontalLayout_26.addWidget(self.radioButton_118)
        self.radioButton_119 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_119.setAutoExclusive(False)
        self.radioButton_119.setObjectName("radioButton_119")
        self.horizontalLayout_26.addWidget(self.radioButton_119)
        self.radioButton_120 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_120.setAutoExclusive(False)
        self.radioButton_120.setObjectName("radioButton_120")
        self.horizontalLayout_26.addWidget(self.radioButton_120)
        self.radioButton_121 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_121.setAutoExclusive(False)
        self.radioButton_121.setObjectName("radioButton_121")
        self.horizontalLayout_26.addWidget(self.radioButton_121)
        self.radioButton_122 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_122.setAutoExclusive(False)
        self.radioButton_122.setObjectName("radioButton_122")
        self.horizontalLayout_26.addWidget(self.radioButton_122)
        self.radioButton_123 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_123.setAutoExclusive(False)
        self.radioButton_123.setObjectName("radioButton_123")
        self.horizontalLayout_26.addWidget(self.radioButton_123)
        self.radioButton_124 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_124.setAutoExclusive(False)
        self.radioButton_124.setObjectName("radioButton_124")
        self.horizontalLayout_26.addWidget(self.radioButton_124)
        self.radioButton_125 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_125.setAutoExclusive(False)
        self.radioButton_125.setObjectName("radioButton_125")
        self.horizontalLayout_26.addWidget(self.radioButton_125)
        self.verticalLayout_5.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.radioButton_110 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_110.setAutoExclusive(False)
        self.radioButton_110.setObjectName("radioButton_110")
        self.horizontalLayout_25.addWidget(self.radioButton_110)
        self.radioButton_111 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_111.setAutoExclusive(False)
        self.radioButton_111.setObjectName("radioButton_111")
        self.horizontalLayout_25.addWidget(self.radioButton_111)
        self.radioButton_112 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_112.setAutoExclusive(False)
        self.radioButton_112.setObjectName("radioButton_112")
        self.horizontalLayout_25.addWidget(self.radioButton_112)
        self.radioButton_113 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_113.setAutoExclusive(False)
        self.radioButton_113.setObjectName("radioButton_113")
        self.horizontalLayout_25.addWidget(self.radioButton_113)
        self.radioButton_114 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_114.setAutoExclusive(False)
        self.radioButton_114.setObjectName("radioButton_114")
        self.horizontalLayout_25.addWidget(self.radioButton_114)
        self.radioButton_115 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_115.setAutoExclusive(False)
        self.radioButton_115.setObjectName("radioButton_115")
        self.horizontalLayout_25.addWidget(self.radioButton_115)
        self.radioButton_116 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_116.setAutoExclusive(False)
        self.radioButton_116.setObjectName("radioButton_116")
        self.horizontalLayout_25.addWidget(self.radioButton_116)
        self.radioButton_117 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_117.setAutoExclusive(False)
        self.radioButton_117.setObjectName("radioButton_117")
        self.horizontalLayout_25.addWidget(self.radioButton_117)
        self.verticalLayout_5.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.radioButton_134 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_134.setAutoExclusive(False)
        self.radioButton_134.setObjectName("radioButton_134")
        self.horizontalLayout_28.addWidget(self.radioButton_134)
        self.radioButton_135 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_135.setAutoExclusive(False)
        self.radioButton_135.setObjectName("radioButton_135")
        self.horizontalLayout_28.addWidget(self.radioButton_135)
        self.radioButton_136 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_136.setAutoExclusive(False)
        self.radioButton_136.setObjectName("radioButton_136")
        self.horizontalLayout_28.addWidget(self.radioButton_136)
        self.radioButton_137 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_137.setAutoExclusive(False)
        self.radioButton_137.setObjectName("radioButton_137")
        self.horizontalLayout_28.addWidget(self.radioButton_137)
        self.radioButton_138 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_138.setAutoExclusive(False)
        self.radioButton_138.setObjectName("radioButton_138")
        self.horizontalLayout_28.addWidget(self.radioButton_138)
        self.radioButton_139 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_139.setAutoExclusive(False)
        self.radioButton_139.setObjectName("radioButton_139")
        self.horizontalLayout_28.addWidget(self.radioButton_139)
        self.radioButton_140 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_140.setAutoExclusive(False)
        self.radioButton_140.setObjectName("radioButton_140")
        self.horizontalLayout_28.addWidget(self.radioButton_140)
        self.radioButton_141 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_141.setAutoExclusive(False)
        self.radioButton_141.setObjectName("radioButton_141")
        self.horizontalLayout_28.addWidget(self.radioButton_141)
        self.verticalLayout_5.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.radioButton_126 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_126.setAutoExclusive(False)
        self.radioButton_126.setObjectName("radioButton_126")
        self.horizontalLayout_27.addWidget(self.radioButton_126)
        self.radioButton_127 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_127.setAutoExclusive(False)
        self.radioButton_127.setObjectName("radioButton_127")
        self.horizontalLayout_27.addWidget(self.radioButton_127)
        self.radioButton_128 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_128.setAutoExclusive(False)
        self.radioButton_128.setObjectName("radioButton_128")
        self.horizontalLayout_27.addWidget(self.radioButton_128)
        self.radioButton_129 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_129.setAutoExclusive(False)
        self.radioButton_129.setObjectName("radioButton_129")
        self.horizontalLayout_27.addWidget(self.radioButton_129)
        self.radioButton_130 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_130.setAutoExclusive(False)
        self.radioButton_130.setObjectName("radioButton_130")
        self.horizontalLayout_27.addWidget(self.radioButton_130)
        self.radioButton_131 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_131.setAutoExclusive(False)
        self.radioButton_131.setObjectName("radioButton_131")
        self.horizontalLayout_27.addWidget(self.radioButton_131)
        self.radioButton_132 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_132.setAutoExclusive(False)
        self.radioButton_132.setObjectName("radioButton_132")
        self.horizontalLayout_27.addWidget(self.radioButton_132)
        self.radioButton_133 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_133.setAutoExclusive(False)
        self.radioButton_133.setObjectName("radioButton_133")
        self.horizontalLayout_27.addWidget(self.radioButton_133)
        self.verticalLayout_5.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.radioButton_103 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_103.setAutoExclusive(False)
        self.radioButton_103.setObjectName("radioButton_103")
        self.horizontalLayout_24.addWidget(self.radioButton_103)
        self.radioButton_104 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_104.setAutoExclusive(False)
        self.radioButton_104.setObjectName("radioButton_104")
        self.horizontalLayout_24.addWidget(self.radioButton_104)
        self.radioButton_105 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_105.setAutoExclusive(False)
        self.radioButton_105.setObjectName("radioButton_105")
        self.horizontalLayout_24.addWidget(self.radioButton_105)
        self.radioButton_106 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_106.setAutoExclusive(False)
        self.radioButton_106.setObjectName("radioButton_106")
        self.horizontalLayout_24.addWidget(self.radioButton_106)
        self.radioButton_107 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_107.setAutoExclusive(False)
        self.radioButton_107.setObjectName("radioButton_107")
        self.horizontalLayout_24.addWidget(self.radioButton_107)
        self.radioButton_108 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_108.setAutoExclusive(False)
        self.radioButton_108.setObjectName("radioButton_108")
        self.horizontalLayout_24.addWidget(self.radioButton_108)
        self.radioButton_109 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_109.setAutoExclusive(False)
        self.radioButton_109.setObjectName("radioButton_109")
        self.horizontalLayout_24.addWidget(self.radioButton_109)
        self.verticalLayout_5.addLayout(self.horizontalLayout_24)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 2, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line.setLineWidth(5)
        self.line.setMidLineWidth(10)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem3)
        self.unfillLbl = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.unfillLbl.setEnabled(True)
        self.unfillLbl.setText("")
        self.unfillLbl.setPixmap(QtGui.QPixmap("../image/unfill_error.png"))
        self.unfillLbl.setObjectName("unfillLbl")
        self.horizontalLayout_17.addWidget(self.unfillLbl)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem5)
        self.backBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.backBtn.setObjectName("backBtn")
        self.horizontalLayout_14.addWidget(self.backBtn)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../image/link_btns.png"))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_14.addWidget(self.label_3)
        self.nextBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.nextBtn.setObjectName("nextBtn")
        self.horizontalLayout_14.addWidget(self.nextBtn)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.endBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.endBtn.setStyleSheet("background-color: rgb(0,255,255)")
        self.endBtn.setObjectName("endBtn")
        self.horizontalLayout_7.addWidget(self.endBtn)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("../image/eclass_lower.png"))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem10)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">職種</span></p></body></html>"))
        self.label_8.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">資格情報</span></p></body></html>"))
        self.label_12.setText(_translate("Form", "TOEIC"))
        self.label_13.setText(_translate("Form", "TOEFL"))
        self.label_9.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">一般</span></p></body></html>"))
        self.label_10.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">教職</span></p></body></html>"))
        self.label_11.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">語学</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">業種</span></p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">希望勤務地</span></p></body></html>"))
        self.radioButton_95.setText(_translate("Form", "北海道"))
        self.radioButton_96.setText(_translate("Form", "青森"))
        self.radioButton_97.setText(_translate("Form", "岩手"))
        self.radioButton_98.setText(_translate("Form", "宮城"))
        self.radioButton_99.setText(_translate("Form", "秋田"))
        self.radioButton_100.setText(_translate("Form", "山形"))
        self.radioButton_101.setText(_translate("Form", "福島"))
        self.radioButton_102.setText(_translate("Form", "茨城"))
        self.radioButton_118.setText(_translate("Form", "栃木"))
        self.radioButton_119.setText(_translate("Form", "群馬"))
        self.radioButton_120.setText(_translate("Form", "埼玉"))
        self.radioButton_121.setText(_translate("Form", "千葉"))
        self.radioButton_122.setText(_translate("Form", "東京"))
        self.radioButton_123.setText(_translate("Form", "神奈川"))
        self.radioButton_124.setText(_translate("Form", "新潟"))
        self.radioButton_125.setText(_translate("Form", "富山"))
        self.radioButton_110.setText(_translate("Form", "石川"))
        self.radioButton_111.setText(_translate("Form", "山梨"))
        self.radioButton_112.setText(_translate("Form", "長野"))
        self.radioButton_113.setText(_translate("Form", "岐阜"))
        self.radioButton_114.setText(_translate("Form", "静岡"))
        self.radioButton_115.setText(_translate("Form", "愛知"))
        self.radioButton_116.setText(_translate("Form", "三重"))
        self.radioButton_117.setText(_translate("Form", "滋賀"))
        self.radioButton_134.setText(_translate("Form", "京都"))
        self.radioButton_135.setText(_translate("Form", "大阪"))
        self.radioButton_136.setText(_translate("Form", "兵庫"))
        self.radioButton_137.setText(_translate("Form", "奈良"))
        self.radioButton_138.setText(_translate("Form", "和歌山"))
        self.radioButton_139.setText(_translate("Form", "鳥取"))
        self.radioButton_140.setText(_translate("Form", "島根"))
        self.radioButton_141.setText(_translate("Form", "岡山"))
        self.radioButton_126.setText(_translate("Form", "広島"))
        self.radioButton_127.setText(_translate("Form", "山口"))
        self.radioButton_128.setText(_translate("Form", "徳島"))
        self.radioButton_129.setText(_translate("Form", "香川"))
        self.radioButton_130.setText(_translate("Form", "愛媛"))
        self.radioButton_131.setText(_translate("Form", "高知"))
        self.radioButton_132.setText(_translate("Form", "福岡"))
        self.radioButton_133.setText(_translate("Form", "佐賀"))
        self.radioButton_103.setText(_translate("Form", "長崎"))
        self.radioButton_104.setText(_translate("Form", "長崎"))
        self.radioButton_105.setText(_translate("Form", "熊本"))
        self.radioButton_106.setText(_translate("Form", "大分"))
        self.radioButton_107.setText(_translate("Form", "宮崎"))
        self.radioButton_108.setText(_translate("Form", "鹿児島"))
        self.radioButton_109.setText(_translate("Form", "沖縄"))
        self.backBtn.setText(_translate("Form", "前へ"))
        self.nextBtn.setText(_translate("Form", "次へ"))
        self.endBtn.setText(_translate("Form", "診断終了"))

