# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design/enaviOutput.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(755, 910)
        Form.setStyleSheet("background-color: rgb(255,255,255);")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(5, 0, 5, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 743, 908))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../image/enavi_header.png"))
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line.setLineWidth(5)
        self.line.setMidLineWidth(10)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.scrollAreaWidgetContents)
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 715, 775))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_11.addWidget(self.label_6)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../image/radar.png"))
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_11.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.line_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_3.addWidget(self.line_3)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout.addWidget(self.scrollArea_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.pdfBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pdfBtn.setStyleSheet("background-color: rgb(0,255,255)")
        self.pdfBtn.setObjectName("pdfBtn")
        self.horizontalLayout_7.addWidget(self.pdfBtn)
        self.homeBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.homeBtn.setStyleSheet("background-color: rgb(0,255,255)")
        self.homeBtn.setObjectName("homeBtn")
        self.horizontalLayout_7.addWidget(self.homeBtn)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../image/eclass_lower.png"))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "進路適性診断 e-navi"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#0000ff;\">お疲れ様でした．</span></p><p><span style=\" font-size:14pt; font-weight:600; text-decoration: underline;\">あなたの性格分析結果</span></p><p><span style=\" font-size:12pt;\">・ あなたは仕事において</span><span style=\" font-size:12pt; font-weight:600;\">達成感</span><span style=\" font-size:12pt;\">を最も重視するようです．</span></p><p><span style=\" font-size:12pt;\">自分の関心がある仕事には積極的な姿勢で向かい合い</span></p><p><span style=\" font-size:12pt;\">困難が生じても，とことん成功を追求することができます．</span></p><p><span style=\" font-size:12pt;\">・</span><span style=\" font-size:12pt; font-weight:600;\"> チームワーク</span><span style=\" font-size:12pt;\">が向いており，中でも自分が率先して仕事を</span></p><p><span style=\" font-size:12pt;\">すすめることを理想としています．</span></p><p><span style=\" font-size:12pt;\">・ ただし，自分のことばかりに集中してしまい，周りを見失う</span></p><p><span style=\" font-size:12pt;\">恐れがあります．また，自分の関心がない仕事やイベントに</span></p><p><span style=\" font-size:12pt;\">対しては，最初から</span><span style=\" font-size:12pt; font-weight:600;\">無頓着</span><span style=\" font-size:12pt;\">であり大きな転機を逃していしまう</span></p><p><span style=\" font-size:12pt;\">危険性もあります．</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">性格分析結果</span></p></body></html>"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; text-decoration: underline;\">あなたの強みとなる3つのスキル</span></p><p><span style=\" font-size:12pt;\">１． あなたは</span><span style=\" font-size:12pt; font-weight:600;\">優れた語学力</span><span style=\" font-size:12pt;\">の持ち主です．</span></p><p><span style=\" font-size:12pt;\">国際的な素養を活かせる環境を見出すことで，あなたの強みが発揮されるでしょう．</span></p><p><span style=\" font-size:12pt;\">2. あなたは</span><span style=\" font-size:12pt; font-weight:600;\">優れた論理的思考力</span><span style=\" font-size:12pt;\">持ち主です．</span></p><p><span style=\" font-size:12pt;\">物事を論理的に理解することや，説明することに長けています．</span></p><p><span style=\" font-size:12pt;\">3． あなたは</span><span style=\" font-size:12pt; font-weight:600;\">優れたプロジェクト遂行能力</span><span style=\" font-size:12pt;\">の持ち主です．</span></p><p>積極的にプロジェクトの中心に立つことがあなたの強みを引き出すでしょう．</p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; text-decoration: underline;\">マッチング企業情報</span></p><p align=\"center\"><span style=\" font-size:12pt; font-style:italic;\">★スキル，志向ともにマッチ！★</span></p><p><span style=\" font-size:14pt;\">GMOペパボ株式会社，　株式会社エウレカ</span></p><p align=\"center\"><span style=\" font-size:12pt; font-style:italic;\">★スキルがマッチ！★</span></p><p><span style=\" font-size:14pt;\">株式会社シーイーシー，　イタンジ株式会社</span></p><p align=\"center\"><span style=\" font-size:12pt; font-style:italic;\">★志向がマッチ！★</span></p><p><span style=\" font-size:14pt;\">株式会社トラント，　株式会社ミスミグループ本社</span></p></body></html>"))
        self.pdfBtn.setText(_translate("Form", "PDF出力"))
        self.homeBtn.setText(_translate("Form", "ホームへ戻る"))

